# Generated by Django 6.0.6 on 2026-07-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmadapp', '0005_alter_ahmadapptask_id_alter_ahmadapptask_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahmadapptask',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='ahmadapptask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
